from __future__ import annotations


COUGH_SYNDROMES: list[dict] = [
    {
        "syndrome": "风寒袭肺",
        "location": ["肺"],
        "nature": ["寒", "实", "外感"],
        "core_symptoms": ["咳嗽声重", "痰白清稀", "恶寒"],
        "supporting_symptoms": ["无汗", "鼻塞流清涕", "头痛", "身痛", "喉痒"],
        "tongue_signs": ["舌苔薄白", "苔薄白"],
        "pulse_signs": ["脉浮紧", "浮紧"],
        "contradictory_signs": ["痰黄黏稠", "口渴", "舌红", "苔黄腻", "脉滑数"],
        "differential_with": ["风热犯肺", "痰湿蕴肺"],
        "pathogenesis": "风寒束表，肺气失宣，气道不利而咳。",
        "treatment_principle": "疏风散寒，宣肺止咳",
        "base_formula": "三拗汤合止嗽散",
        "formula_explanation": [
            {"herb_or_group": "宣肺散寒药组", "role": "君", "target_pathogenesis": "疏散风寒，宣通肺气"},
            {"herb_or_group": "止咳化痰药组", "role": "臣", "target_pathogenesis": "缓解肺气上逆与痰阻"},
            {"herb_or_group": "调和药组", "role": "佐使", "target_pathogenesis": "协调宣降，兼顾咽喉不利"},
        ],
        "modification_rules": [
            {"condition": ["鼻塞流清涕"], "adjustment": "加强疏风通窍方向", "reason": "风寒束表并见鼻窍不利"},
            {"condition": ["痰多"], "adjustment": "加强燥湿化痰方向", "reason": "兼有痰湿阻肺"},
        ],
    },
    {
        "syndrome": "风热犯肺",
        "location": ["肺"],
        "nature": ["热", "实", "外感"],
        "core_symptoms": ["咳嗽频剧", "咽痛", "发热恶风"],
        "supporting_symptoms": ["痰黄", "口渴", "鼻流黄涕", "头痛"],
        "tongue_signs": ["舌尖红", "苔薄黄", "舌红"],
        "pulse_signs": ["脉浮数", "浮数"],
        "contradictory_signs": ["恶寒", "无汗", "痰白清稀", "脉浮紧", "苔白"],
        "differential_with": ["风寒袭肺", "痰热郁肺", "风燥伤肺"],
        "pathogenesis": "风热犯肺，肺失清肃，肺气上逆。",
        "treatment_principle": "疏风清热，宣肺止咳",
        "base_formula": "桑菊饮",
        "formula_explanation": [
            {"herb_or_group": "疏风清热药组", "role": "君", "target_pathogenesis": "疏散在表风热"},
            {"herb_or_group": "宣肺止咳药组", "role": "臣", "target_pathogenesis": "恢复肺气宣降"},
            {"herb_or_group": "清利咽喉药组", "role": "佐", "target_pathogenesis": "缓解风热上扰咽喉"},
        ],
        "modification_rules": [
            {"condition": ["咽痛"], "adjustment": "加强清利咽喉方向", "reason": "风热上扰咽喉较著"},
            {"condition": ["口渴"], "adjustment": "兼顾清热生津方向", "reason": "热邪耗津"},
        ],
    },
    {
        "syndrome": "风燥伤肺",
        "location": ["肺"],
        "nature": ["燥", "实", "外感"],
        "core_symptoms": ["干咳", "痰少黏稠", "咽干"],
        "supporting_symptoms": ["鼻燥", "口干", "咽痒", "微恶风"],
        "tongue_signs": ["舌红少津", "苔薄白而干", "苔薄黄而干"],
        "pulse_signs": ["脉浮数", "脉浮"],
        "contradictory_signs": ["痰多", "痰白清稀", "苔黄腻", "脉滑"],
        "differential_with": ["风热犯肺", "肺阴亏耗"],
        "pathogenesis": "燥邪伤肺，耗津灼液，肺失清润。",
        "treatment_principle": "疏风清肺，润燥止咳",
        "base_formula": "桑杏汤",
        "formula_explanation": [
            {"herb_or_group": "轻宣燥热药组", "role": "君", "target_pathogenesis": "疏解外燥，清宣肺气"},
            {"herb_or_group": "润肺止咳药组", "role": "臣", "target_pathogenesis": "补充肺津，缓解干咳"},
            {"herb_or_group": "清热生津药组", "role": "佐", "target_pathogenesis": "兼清燥热、保护津液"},
        ],
        "modification_rules": [
            {"condition": ["咽干"], "adjustment": "加强养阴润咽方向", "reason": "燥邪耗伤咽喉津液"},
            {"condition": ["痰中带血"], "adjustment": "停止方剂展示并提示医学评估", "reason": "属于需要优先排查的危险信号"},
        ],
    },
    {
        "syndrome": "痰湿蕴肺",
        "location": ["肺", "脾"],
        "nature": ["湿", "痰", "实"],
        "core_symptoms": ["咳嗽反复", "痰多", "痰白黏腻"],
        "supporting_symptoms": ["胸闷", "食少", "脘痞", "晨起咳甚", "体倦"],
        "tongue_signs": ["舌淡", "苔白腻"],
        "pulse_signs": ["脉濡滑", "脉滑", "濡滑"],
        "contradictory_signs": ["痰黄黏稠", "舌红少苔", "咽干", "脉细数"],
        "differential_with": ["痰热郁肺", "肺气虚", "风寒袭肺"],
        "pathogenesis": "脾失健运，痰湿内生，上渍于肺，肺气不利。",
        "treatment_principle": "燥湿化痰，理气止咳",
        "base_formula": "二陈平胃散合三子养亲汤",
        "formula_explanation": [
            {"herb_or_group": "燥湿化痰药组", "role": "君", "target_pathogenesis": "化解蕴肺痰湿"},
            {"herb_or_group": "健脾理气药组", "role": "臣", "target_pathogenesis": "恢复运化，减少痰源"},
            {"herb_or_group": "降气止咳药组", "role": "佐", "target_pathogenesis": "调畅肺气，缓解咳逆"},
        ],
        "modification_rules": [
            {"condition": ["胸闷"], "adjustment": "加强理气宽胸方向", "reason": "痰湿阻滞胸中气机"},
            {"condition": ["食少"], "adjustment": "加强健脾助运方向", "reason": "脾运不足是生痰之源"},
        ],
    },
    {
        "syndrome": "痰热郁肺",
        "location": ["肺"],
        "nature": ["热", "痰", "实"],
        "core_symptoms": ["痰黄黏稠", "咳嗽气粗", "痰难咯"],
        "supporting_symptoms": ["口渴", "胸闷", "发热", "口苦"],
        "tongue_signs": ["舌红", "苔黄腻"],
        "pulse_signs": ["脉滑数", "滑数"],
        "contradictory_signs": ["痰白清稀", "恶寒", "无汗", "舌淡", "脉沉细"],
        "differential_with": ["风热犯肺", "痰湿蕴肺", "肝火犯肺"],
        "pathogenesis": "痰热壅肺，肺失清肃，气逆而咳。",
        "treatment_principle": "清热肃肺，豁痰止咳",
        "base_formula": "清金化痰汤",
        "formula_explanation": [
            {"herb_or_group": "清肺热药组", "role": "君", "target_pathogenesis": "针对痰热壅肺中的“热”"},
            {"herb_or_group": "化痰药组", "role": "臣", "target_pathogenesis": "针对痰黏难咯中的“痰”"},
            {"herb_or_group": "理气药组", "role": "佐", "target_pathogenesis": "改善肺气不利、胸闷咳逆"},
        ],
        "modification_rules": [
            {"condition": ["胸闷"], "adjustment": "加强理气宽胸方向", "reason": "痰热阻滞肺络与胸中气机"},
            {"condition": ["口渴"], "adjustment": "兼顾清热生津方向", "reason": "里热耗伤津液"},
        ],
    },
    {
        "syndrome": "肝火犯肺",
        "location": ["肝", "肺"],
        "nature": ["热", "实"],
        "core_symptoms": ["咳嗽与情绪相关", "胸胁胀痛", "咳嗽阵作"],
        "supporting_symptoms": ["口苦", "咽干", "面红", "急躁易怒"],
        "tongue_signs": ["舌红", "苔薄黄"],
        "pulse_signs": ["脉弦数", "弦数"],
        "contradictory_signs": ["痰白清稀", "恶寒", "无汗", "舌淡胖"],
        "differential_with": ["痰热郁肺", "肺阴亏耗"],
        "pathogenesis": "肝郁化火，上逆侮肺，肺失肃降。",
        "treatment_principle": "清肺泻肝，顺气降火",
        "base_formula": "黛蛤散合泻白散",
        "formula_explanation": [
            {"herb_or_group": "清肝泻火药组", "role": "君", "target_pathogenesis": "平降上逆之肝火"},
            {"herb_or_group": "清肺止咳药组", "role": "臣", "target_pathogenesis": "恢复肺气肃降"},
            {"herb_or_group": "理气和络药组", "role": "佐", "target_pathogenesis": "缓解胸胁气机不畅"},
        ],
        "modification_rules": [
            {"condition": ["胸胁胀痛"], "adjustment": "加强疏肝理气方向", "reason": "肝经气机郁滞表现突出"},
            {"condition": ["口苦"], "adjustment": "加强清肝泄热方向", "reason": "肝胆郁热上蒸"},
        ],
    },
    {
        "syndrome": "肺阴亏耗",
        "location": ["肺"],
        "nature": ["虚", "燥", "阴虚"],
        "core_symptoms": ["干咳少痰", "咽干", "咳声短促"],
        "supporting_symptoms": ["午后潮热", "盗汗", "消瘦", "声音嘶哑", "口干"],
        "tongue_signs": ["舌红少苔", "舌红少津"],
        "pulse_signs": ["脉细数", "细数"],
        "contradictory_signs": ["痰多", "苔厚腻", "痰白清稀", "脉滑"],
        "differential_with": ["风燥伤肺", "肺气虚"],
        "pathogenesis": "肺阴亏虚，虚热内生，肺失濡润。",
        "treatment_principle": "滋阴润肺，化痰止咳",
        "base_formula": "沙参麦冬汤",
        "formula_explanation": [
            {"herb_or_group": "滋养肺阴药组", "role": "君", "target_pathogenesis": "补益耗伤之肺阴"},
            {"herb_or_group": "润燥生津药组", "role": "臣", "target_pathogenesis": "改善咽干、少痰"},
            {"herb_or_group": "清虚热止咳药组", "role": "佐", "target_pathogenesis": "缓解虚热与肺气上逆"},
        ],
        "modification_rules": [
            {"condition": ["盗汗"], "adjustment": "加强敛汗固表方向", "reason": "阴虚不能敛阳"},
            {"condition": ["声音嘶哑"], "adjustment": "加强养阴利咽方向", "reason": "肺阴不足，咽喉失润"},
        ],
    },
    {
        "syndrome": "肺气虚",
        "location": ["肺", "脾"],
        "nature": ["虚", "气虚"],
        "core_symptoms": ["咳嗽无力", "气短乏力", "动则咳甚"],
        "supporting_symptoms": ["自汗", "畏风", "神疲乏力", "易感冒", "声音低弱"],
        "tongue_signs": ["舌淡", "舌淡胖"],
        "pulse_signs": ["脉虚弱", "脉沉细", "脉弱"],
        "contradictory_signs": ["痰黄黏稠", "高热", "舌红", "苔黄腻", "脉滑数"],
        "differential_with": ["肺阴亏耗", "痰湿蕴肺"],
        "pathogenesis": "肺气亏虚，宣降无权，卫外不固。",
        "treatment_principle": "补益肺气，化痰止咳",
        "base_formula": "补肺汤",
        "formula_explanation": [
            {"herb_or_group": "补益肺气药组", "role": "君", "target_pathogenesis": "恢复肺主气、司呼吸之能"},
            {"herb_or_group": "健脾益气药组", "role": "臣", "target_pathogenesis": "培土生金，充养肺气"},
            {"herb_or_group": "敛肺止咳药组", "role": "佐", "target_pathogenesis": "改善久咳耗气与肺气不敛"},
        ],
        "modification_rules": [
            {"condition": ["自汗"], "adjustment": "加强益气固表方向", "reason": "肺气虚弱，卫表不固"},
            {"condition": ["痰多"], "adjustment": "兼顾健脾化痰方向", "reason": "气虚运化无力而生痰"},
        ],
    },
]


SYNDROME_BY_NAME = {item["syndrome"]: item for item in COUGH_SYNDROMES}


EXAMPLE_CASES = [
    {
        "id": "phlegm-heat",
        "title": "痰黄黏稠 · 口渴",
        "hint": "里热与痰象较完整",
        "symptoms": ["咳嗽气粗", "痰黄黏稠", "痰难咯", "口渴", "胸闷"],
        "tongue": "舌红，苔黄腻",
        "pulse": "脉滑数",
        "other_information": "病程5天，无明显恶寒。",
    },
    {
        "id": "wind-cold",
        "title": "声重痰白 · 恶寒",
        "hint": "外感风寒线索集中",
        "symptoms": ["咳嗽声重", "痰白清稀", "恶寒", "无汗", "鼻塞流清涕"],
        "tongue": "舌淡红，苔薄白",
        "pulse": "脉浮紧",
        "other_information": "受凉后起病2天。",
    },
    {
        "id": "lung-yin",
        "title": "干咳少痰 · 咽干",
        "hint": "阴亏失润表现",
        "symptoms": ["干咳少痰", "咽干", "咳声短促", "声音嘶哑"],
        "tongue": "舌红少苔",
        "pulse": "脉细数",
        "other_information": "咳嗽反复两月，午后较重。",
    },
    {
        "id": "liver-fire",
        "title": "情绪相关 · 胸胁胀",
        "hint": "肝肺同病鉴别",
        "symptoms": ["咳嗽与情绪相关", "胸胁胀痛", "咳嗽阵作", "口苦", "急躁易怒"],
        "tongue": "舌红，苔薄黄",
        "pulse": "脉弦数",
        "other_information": "情绪波动后咳嗽明显。",
    },
    {
        "id": "insufficient",
        "title": "咳嗽 · 痰多",
        "hint": "体验信息不足如何处理",
        "symptoms": ["咳嗽", "痰多"],
        "tongue": "",
        "pulse": "",
        "other_information": "尚未补充痰色、寒热与病程。",
    },
]
